name: Build

on:
  push:
    branches-ignore:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: source
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true
    - name: Install ImageMagick
      run: |
        sudo apt-get update
        sudo apt-get install -y imagemagick
    - name: Build Jekyll site
      run: |
        set -xo pipefail
        rm -rf _site
        JEKYLL_ENV=production bundle exec jekyll build
    - name: Deploy
      if: github.ref == 'refs/heads/source'
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      run: |
        set -xo pipefail
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git fetch origin master:master
        git checkout master
        ls -Q | grep -v _site | xargs rm -rf
        mv _site/* .
        rm -rf _site
        rm -rf .jekyll-cache
        [[ -n "$(git status --porcelain)" ]] || exit 0
        git add .
        git commit -m "Build $(git rev-parse source | grep -o '^.\{10\}')"
        git push "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git" master
